apiVersion: v1
kind: Service
metadata:
  name: prometheus-community-grafana-nodeport
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: prometheus-community
    app.kubernetes.io/name: grafana
spec:
  type: NodePort
  ports:
    - name: http-web
      port: 80
      targetPort: 3000
      nodePort: 30530
  selector:
    app.kubernetes.io/instance: prometheus-community
    app.kubernetes.io/name: grafana
