global:
prometheus:
  prometheusSpec:
    scrapeInterval: 15s
    additionalScrapeConfigs:
      - job_name: 'karmada-scheduler'
        kubernetes_sd_configs:
        - role: pod
        scheme: http
        tls_config:
          insecure_skip_verify: true
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app]
          action: keep
          regex: karmada-system;karmada-scheduler
        - target_label: __address__
          source_labels: [__address__]
          regex: '(.*)'
          replacement: '${1}:10351'
          action: replace
      - job_name: 'karmada-controller-manager'
        kubernetes_sd_configs:
        - role: pod
        scheme: http
        tls_config:
          insecure_skip_verify: true
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app]
          action: keep
          regex: karmada-system;karmada-controller-manager
        - target_label: __address__
          source_labels: [__meta_kubernetes_pod_ip]
          replacement: '${1}:8080'
          action: replace
      - job_name: 'karmada-apiserver'
        kubernetes_sd_configs:
        - role: endpoints
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token: <secret-token>
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: karmada-apiserver
        - target_label: __address__
          replacement: karmada-apiserver.karmada-system.svc:5443
      - job_name: 'karmada-aggregated-apiserver'
        kubernetes_sd_configs:
        - role: endpoints
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token: <secret-token>
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoints_name]
          action: keep
          regex: karmada-system;karmada-aggregated-apiserver;karmada-aggregated-apiserver
        - target_label: __address__
          replacement: karmada-aggregated-apiserver.karmada-system.svc:443
  additionalRulesForClusterRole:
      - apiGroups:
        - ''
        resources:
        - nodes
        - nodes/proxy
        - services
        - endpoints
        - pods
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - extensions
        resources:
        - ingresses
        verbs:
        - get
        - list
        - watch
      - nonResourceURLs:
        - /metrics
        verbs:
        - get
      - apiGroups:
        - cluster.karmada.io
        resources:
        - '*'
        verbs:
        - '*'
